#preload = /home/doaads/Pictures/wallpaper.jpg
#wallpaper = eDP-1, /home/doaads/Pictures/wallpaper.jpg

wallpaper {
monitor = eDP-1
path = /home/doaads/Pictures/wallpaper.jpg
fit_mode = cover
}

wallpaper {
monitor = HDMI-A-1
path = /home/doaads/Pictures/wallpaper.jpg
fit_mode = cover
}

splash = false
ipc = off
